### ISSUE TITLE
Add windows patch

### ISSUE THREAD

**Issue by ghost** [Muril-o/electron-chromium-codecs#1]
Add windows changes to patch now that I know for sure this patch works on windows too thanks to Kirdow.

**Comment by Alex313031** [comment]
@Muril-o Yes, these work on Linux, Windows, AND MacOS. I use it for Thorium, as I said before, and we make builds for many OSes.

However, it does not seem to work for any ARM/ARM64 platforms. When compiling for Android, Raspberry Pi, or MacOS M1 (arm64), it complains about the .asm files, which I am assuming is only x86 assembly.
