### ISSUE TITLE
Update patches.

### ISSUE THREAD

**Issue by Alex313031** [Muril-o/electron-chromium-codecs#6]
Hi, I use this patch as well as https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding as a basis for making my own patch to enable hevc and ac3/eac3 in my chromium fork thorium > https://thorium.rocks/

Could you maybe update the patchset for latest or newer electron?

**Comment by ghost** [comment]
> Could you maybe update the patchset for latest or newer electron?

While I would like to, I don't have enough SSD space to do it right now. So I just ordered an SSD, should arrive next week.

**Comment by ghost** [comment]
17be315

**Comment by Alex313031** [comment]
@Muril-o Thanks a bunch. @gz83 @midzer We can use the electron 25.x.x patch for Thorium 115. There are two lines that differ from the current way that I am adding AC3 support, so thats good.

These: 
https://github.com/Muril-o/electron-chromium-codecs/blob/main/v25.1.0/look_ffmpeg_hevc_ac3.patch#L37
and
https://github.com/Muril-o/electron-chromium-codecs/blob/main/v25.1.0/look_ffmpeg_hevc_ac3.patch#L50

IDK what they do, but considering that AC3 seems to work in the current release, these lines might enable specific formats or edge cases.
